/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3fa49617-4ec2-4521-b433-a7925d5c4509",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ut7bg8mAj",
    "aws_user_pools_web_client_id": "59icephrchuu44981gncrseae1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rsujjwrldbaz7cw6xvwygj2yom.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "privatecondobucket123155-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
